name: Publicar receitas

on:
  push:
    paths:
      - "site/Receitas Testadas/*.txt"
  workflow_dispatch: # permite rodar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências (se houver)
        run: |
          python -m pip install --upgrade pip

      - name: Gerar JSON de receitas
        run: python atualizar_receitas.py

      - name: Commit e push automáticos
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add site/Receitas\ Testadas/receitas_testadas.json
          git commit -m "Atualiza lista de receitas automaticamente" || echo "Nada a commitar"
          git push
